name: FGO Login System

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 22 * * *"
    - cron: "0 06 * * *"
    - cron: "0 14 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Getting files from Repo
        uses: actions/checkout@v2

      - name: Installing python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Execute main script
        run: |
          python3 main.py
        env:
          userIds: ${{ secrets.GAME_USERIDS }}
          authKeys: ${{ secrets.GAME_AUTHKEYS }}
          secretKeys: ${{ secrets.GAME_SECRETKEYS }}
          UserAgent: ${{ secrets.GAME_USERAGENT }}
          fateRegion: ${{ secrets.GAME_REGION }}
          webhookDiscord: ${{ secrets.DISCORD_WEBHOOK }}
